<?php

namespace Blog\Bundle\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function findAllOrderByCreate()
    {
        return $this->createQueryBuilder('m')
            ->orderBy('m.createdAt')
            ->getQuery()
            ;
    }
}
