<?php

namespace Blog\Bundle\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findAllByNewest()
    {
        return $this->createQueryBuilder('p')
            ->select('p', 'c')
            ->leftJoin('p.comments', 'c')
            ->OrderBy('p.createdAt')
            ->getQuery()
            ->getResult()
            ;
    }
}
