<?php
//
//namespace Blog\Bundle\BlogBundle\Entity;
//
//use Doctrine\ORM\EntityRepository;
//
///**
// * TagRepository
// *
// * This class was generated by the Doctrine ORM. Add your own custom
// * repository methods below.
// */
//class TagRepository extends EntityRepository
//{
//    public function getTags()
//    {
//        $postTags = $this->createQuery(
//            'SELECT t.title
//            FROM BlogBlogBundle:Tag')
//            ->execute();
//
//        $tags = array();
//        foreach ($postTags as $postTag)
//        {
//            $tags = array_merge(explode(",", $postTag['tags']), $tags);
//        }
//
//        foreach ($tags as &$tag)
//        {
//            $tag = trim($tag);
//        }
//
//        return $tags;
//    }
//
//    public function getTagWeight($tags)
//    {
//        $tagWeights = array();
//
//        if(empty($tags)) {
//            return $tagWeights;
//        }
//
//        foreach ($tags as $tag)
//        {
//            $tagWeights[$tag] = (isset($tagWeights[$tag])) ? $tagWeights[$tag]+1 : 1;
//        }
//
//        $max = max($tagWeights);
//
//        $multiple = ($max > 5) ? 5 / $max :1;
//        foreach ($tagWeights as &$tag)
//        {
//            $tag = ceil($tag * $multiple);
//        }
//
//        return $tagWeights;
//
//    }
//
//}
