home_page:
    path: /
    defaults: { _controller: BlogBlogBundle:Default:index }

about_page:
    path: /about
    defaults: { _controller: BlogBlogBundle:Default:about }

post_page:
    path: /post
    defaults: { _controller: BlogBlogBundle:Default:post }

guestbook:
    path:  /gbook
    defaults: { _controller: BlogBlogBundle:Default:guestbook }
