home_page:
    path: /
    defaults: { _controller: BlogBlogBundle:Default:index }

about_page:
    path: /about
    defaults: { _controller: BlogBlogBundle:Default:about }

post_page:
    path: /post
    defaults: { _controller: BlogBlogBundle:Default:post }

show_post_page:
    path: /{id}
    defaults: { _controller: BlogBlogBundle:Default:showPost }
    requirements:
            id: \d+

guestbook:
    path:  /gbook
    defaults: { _controller: BlogBlogBundle:Default:guestbook }
