services:
    form.type.message:
        class: Blog\Bundle\BlogBundle\Form\Type\MessageType
        tags:
            - { name: form.type, alias: message }

    blog.pagination:
        class: Blog\Bundle\BlogBundle\PagePagination
        arguments:
            - @doctrine.orm.entity_manager
        calls:
            - [setPerPage, [10]]

    twig.extension.text:
           class: Twig_Extensions_Extension_Text
           tags:
               - { name: twig.extension }